# Generated by Django 2.1.3 on 2018-12-28 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dahlia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dahlia.Revision')),
            ],
        ),
    ]
