# Generated by Django 2.1.5 on 2019-08-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecilia', '0002_auto_20181114_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
